# Generated by Django 5.2 on 2025-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options_tenant_email_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="subdomain",
        ),
        migrations.AddField(
            model_name="tenant",
            name="domain",
            field=models.CharField(default="pos.com", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
