# Generated by Django 5.2 on 2025-12-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_tenant_subdomain_tenant_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.tenant",
            ),
        ),
    ]
